### PR TITLE
add galaxy collection badge

### PR DESCRIPTION
**Pull request by artis3n**
~Made this on an iPad, I'll make a fragment in a bit. Also the generated markdown hyperlink is...not correct. I'll update.~

The added badges use [DO's brand color](https://www.brandcolorcode.com/digitalocean).

Double check my responses: https://www.bestpractices.dev/en/projects/7862

### CODE REVIEW

**Review by mamercad — APPROVED** [review]
The badge looks nice!

**Comment by artis3n** [comment]
@mamercad Preferred style? In line with the other badges on the README

1. Ansible Collection


2. Ansible Collection

3. Ansible Collection

**Comment by mamercad** [comment]
> ~Made this on an iPad, I'll make a fragment in a bit. Also the generated markdown hyperlink is...not correct. I'll update.~
> 
> The added badges use [DO's brand color](https://www.brandcolorcode.com/digitalocean).
> 
> Double check my responses: https://www.bestpractices.dev/en/projects/7862

Very nice, I'll check your responses and report back!

**Comment by mamercad** [comment]
> @mamercad Preferred style?
> 
> 1. Ansible Collection
> 2. Ansible Collection
> 3. Ansible Collection

Can we do "Ansible Collection | digialocean.cloud", I think "Ansible Collection" is perhaps a proper noun and we capitalize both words?

**Comment by mamercad** [comment]
> > @mamercad Preferred style?
> > 
> > 1. Ansible Collection
> > 2. Ansible Collection
> > 3. Ansible Collection
> 
> Can we do `Ansible Collection | digitalocean.cloud`, I think "Ansible Collection" is perhaps a proper noun and we capitalize both words?

And I think 3 with the rounded borders to match the rest of the badges.

**Comment by mamercad** [comment]
> ~Made this on an iPad, I'll make a fragment in a bit. Also the generated markdown hyperlink is...not correct. I'll update.~
> 
> The added badges use [DO's brand color](https://www.brandcolorcode.com/digitalocean).
> 
> Double check my responses: https://www.bestpractices.dev/en/projects/7862

I've gone through the OpenSSF responses, and, they look good to me :ship:

**Review by mamercad — APPROVED** [review]
Looking good, 🚢

**Pull request merged**
